# === CONFIG ===
BASE_URL = "https://www.cv-prod-euwest-2.arista.io/cvpservice"
ACCESS_TOKEN = "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjY5NTkxNjIyNjczNTUxNTM3NDksImRzdCI6InVzZXIiLCJleHAiOjE3NjY2NTAyNjUsImlhdCI6MTc2NjU2Mzg2Niwib2dpIjo2OTU5MTYyMjY3MzU1MDY5MjM2LCJvZ24iOiJrYXNpY2xvdWQiLCJzaWQiOiIwMTliNGY2OS02MWI1LTdhYzQtODM2NC1jZjUyYzdjOTBhMWMifQ.V-p9PkP4dqMWH_zifoTtZUdWMTfbJfl5S2D-TBUWnfVZzqXIB0BxIR-gVlVZ6bxeDg99GR4wkbT2dUPJt2qOFw"
TARGET_HOSTNAME = "KASI-LOS5-R201-BG01"
START_INDEX = 28  # change this to resume from a later index